name: design_system
description: Tema claro/oscuro, tokens MARQUEE, componentes y animaciones base.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

resolution: workspace

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
